Header: '&2-----------------------------------------------------'
StaffOnline: '&eStaff Online: %staffonline%'
Helpers: '&eHelpers: %helpers%'
Moderators: '&eModerators: %moderators%'
Administrators: '&eAdministrators: %administrators%'
Owners: '&eOwners: %owners%'
Footer: '&2-----------------------------------------------------'
Helpers/TraineesNameColor: '&d'
ModeratorsNameColor: '&6'
AdministratorsNameColor: '&3'
OwnersNameColor: '&c'